-- 코드를 입력하세요

SELECT USER_ID
     , NICKNAME
     , CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2  AS 전체주소
     , SUBSTR(u.TLNO,1,3)||'-'||SUBSTR(u.TLNO,4,4)||'-'||SUBSTR(u.TLNO,8,4) AS 전화번호
 FROM USED_GOODS_USER u,
        (SELECT WRITER_ID ,COUNT(WRITER_ID) AS CNT
          FROM USED_GOODS_BOARD
         GROUP BY WRITER_ID) b
 WHERE u.USER_ID = b.WRITER_ID
   AND b.CNT >= 3
 ORDER BY u.USER_ID DESC
   ;