-- 코드를 입력하세요

SELECT c.CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h, CAR_RENTAL_COMPANY_CAR c
 WHERE h.CAR_ID = c.CAR_ID
   AND EXTRACT(MONTH FROM h.START_DATE) = 10 
   AND c.CAR_TYPE = '세단'
 GROUP BY c.CAR_ID
 ORDER BY c.CAR_ID DESC
 
