-- 코드를 입력하세요
SELECT '/home/grep/src/'||f.BOARD_ID||'/'||f.FILE_ID||f.FILE_NAME||f.FILE_EXT AS FILE_PATH
  FROM USED_GOODS_BOARD d, USED_GOODS_FILE f
 WHERE d.BOARD_ID = f.BOARD_ID
   AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
  ORDER BY FILE_ID DESC
  ;