-- 코드를 입력하세요
SELECT b.CATEGORY AS CATEGORY ,
       SUM(s.SALES) AS TOTAL_SALES
  FROM BOOK b, BOOK_SALES s
 WHERE b.BOOK_ID = s.BOOK_ID
   AND TO_CHAR(SALES_DATE,'MM') IN '01'
 GROUP BY b.CATEGORY
 ORDER BY CATEGORY 
  ;